// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOKElOa9FRlKH574f-vqmj8jRM-6Xxxbg',
    appId: '1:859405970394:web:1699fa4f37ad3c52b3eee3',
    messagingSenderId: '859405970394',
    projectId: 'chat-app-e87b2',
    authDomain: 'chat-app-e87b2.firebaseapp.com',
    storageBucket: 'chat-app-e87b2.appspot.com',
    measurementId: 'G-8X6B92EPQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmwfCz7m9mNU6J-52kUQFUQx4VLDYvuWA',
    appId: '1:859405970394:android:7403a3d6aea28b9db3eee3',
    messagingSenderId: '859405970394',
    projectId: 'chat-app-e87b2',
    storageBucket: 'chat-app-e87b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjocHBvvAixHv6JDjX6YtB84O3_nK4ygY',
    appId: '1:859405970394:ios:28ae3ae5d84bc427b3eee3',
    messagingSenderId: '859405970394',
    projectId: 'chat-app-e87b2',
    storageBucket: 'chat-app-e87b2.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
